### PR TITLE
Add issues/PR templates

### PR DESCRIPTION
**Pull request by AnnaSmoot-NOAA**
## DESCRIPTION OF CHANGES: 
Adding issue and PR Templates. 

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## TESTS CONDUCTED: 

- [X] gaea.intel
- [X] hera.intel
- [ ] wcoss2.intel

## CHECKLIST

- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [ ] My changes do not require updates to the documentation (explain).
- [X] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

## PRIOTIRY LEVEL

- [ ] Critical: emergency fix for a major issue
- [ ] High: upcoming production fix/change 
- [X] Normal: important but not high priority
- [ ] Low: routine addition or bonus feature that can wait

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
I think the PR template only needs gaea/hera/wcoss2 for testing as those are the only current systems we've agreed to support at this time.

**Comment by BrianCurtis-NOAA** [comment]
@AnnaSmoot-NOAA What is your opinion on this labels idea?: As CM's we should be reading through PR's and assigning labels on our own. There should be no need to ask the PR author to checkbox any.

For example: priority can be determined at the weekly internal meetings where we discuss the current slate of PR's. If a user needs helps they can comment on their issues/PR's with that. A PR should be defined as "ready to go" when the author changes from draft to ready for review.

**Comment by AnnaSmoot-NOAA** [comment]
I updated the PR template to only include Gaea, Hera, and WCOSS and removed the labels options. I like the idea of us labeling them ourselves. I think that will streamline the work/communication better.

**Comment by BrianCurtis-NOAA** [comment]
Two more things:
- We should have a section for the author to set their anticipated priority, say Critical, High, Normal where Critical would be an emergecy fix that needs to get in ASAP that fixes a major current issue. High would be for an upcoming production fix/change. Normal would hopefully be self explanitory.
- The title suggests you're bringing in the changes to Externals.cfg but none of the changes files in this PR show that file with changes.

**Comment by AnnaSmoot-NOAA** [comment]
1. I added a priority section to this PR and the PR template. 
2.  The second part of the Description of Changes mentions updating Externals.cfg. I also added some more information under Tests Conducted. 
3. Should this PR have any dependencies/external PRs?

**Comment by AnnaSmoot-NOAA** [comment]
I realized the modified files also include the updated .app_build.sh that is needed for both Gaea C6 and Hera. I created issue #6  and added it to this PR.

**Pull request closed without merging**
